### ISSUE TITLE
got 404 using the example app

### ISSUE THREAD

**Issue by herry1234** [mulesoft/osprey#105]
main.js: 

```
ar express = require('express')
var osprey = require('osprey')
var join = require('path').join

var PORT = process.env.PORT || 3000

var router = osprey.Router()

router.get('/users', function (req, res) {
    console.log("eeeee");
  res.json([
    {
      username: 'blakeembrey',
      password: 'hunter2'
    }
  ])
})

osprey.loadFile(join(__dirname, 'api.raml'))
  .then(function (middleware) {
    var app = express()

    app.use('/api', middleware, router)

    app.listen(PORT, function () {
      console.log('Application listening on ' + PORT + '...')
    })
  })
```

api.raml

```
#%RAML 0.8
title: Example API
version: v1
baseUri: http://127.0.0.1:3000/api

/users:
  get:
    queryParameters:
      sort:
        enum: [username, name]
```

node
node --version
v4.2.6
