### ISSUE TITLE
Pass annotation values to handler?

### ISSUE THREAD

**Issue by memelet** [mulesoft/osprey#124]
Is there anyway to pass annotation values to a handler? eg,

```
annotationTypes:
  permissions:
    type: string

/users:
  get:
    (permissions): 'foo:bar'
    queryParameters:
      sort:
        enum: [username, name]
```

The application middleware needs the required permissions value to validate against the JWT.
