### ISSUE TITLE
Does Osprey support union types?

### ISSUE THREAD

**Issue by zero51** [mulesoft/osprey#126]
If I have two types...
```
types:
  Email:
    type: string
  ID:
    type: integer
```
And a union of the two...
```
  UserIdentifier:
    type: ID | Email
```
Then Osprey throws a 404 whenever I try to access a route that uses the union type in a URI parameter...
```
    /users:
      /{identifier}:
        uriParameters: 
          identifier: 
            type: UserIdentifier
```
Using either type on its own works fine.
