### ISSUE TITLE
Does Osprey support minProperties?

### ISSUE THREAD

**Issue by zero51** [mulesoft/osprey#127]
With the following RAML...
```
        patch:
          body:
            application/json:
              type: object
              properties:
                firstName?: string
                lastName?: string
              additionalProperties: false
              minProperties: 1
```
I would expect a request with blank body to fail, but it succeeds.

**Comment by zero51** [comment]
Ditto `additionalProperties`. It seems to be ignored, which is a shame...

**Comment by zero51** [comment]
@jstoiko: any guidance here? This and #126 are quite important to us. It's a great library, but there seems to be little activity. Is it still actively maintained?

**Comment by jstoiko** [comment]
@zero51: you raised some valid points. I should be able to get back to you by the end of the week with a solution to both issues. 

Yes, this project is still actively maintained and a version with RAML 1.0 should be released soon. It's taking more time than expected to get it out and it's out of my control. Thanks for your patience.

**Comment by zero51** [comment]
Thanks @jstoiko. I'm using the raml1.0 branch at the moment, and most of it works fine.

**Comment by jstoiko** [comment]
Hang in there @zero51, still working on addressing this and #126. Not as trivial as I originally thought. Shouldn't be much longer though. The good news is we'll be able to include those changes in the new (pending) release.

**Comment by zero51** [comment]
Thanks for the update @jstoiko. Looking forward to playing with the new release...

**Comment by jstoiko** [comment]
@zero51: `minProperties`, `maxProperties` and `additionalProperties` should work now. Can you give it a shot?

**Comment by zero51** [comment]
@jstoiko: `minProperties` seems to work now, although `additionalProperties` is still ignored. Also, I'm getting parse errors now on the RAML doc, even though Atom doesn't complain...

```
[xmldom error]	element parse error: Error: invalid tagName:<resourcePathName 
@#[line:1,col:17]
[xmldom warning]	unclosed xml attribute 
@#[line:1,col:18]
```
and

```
[xmldom error]	element parse error: Error: invalid tagName:<resourcePathName 
@#[line:1,col:14]
[xmldom warning]	attribute "|" missed value!! "|" instead2!! 
@#[line:1,col:15]
```

I have two resource types defined, which do make use of resourcePathName tags, but their implementation has not changed.

**Comment by zero51** [comment]
Removing all the resource-type descriptions silences all but two parse errors. There was nothing particuarly special about them...

```
description: Where the <<resourcePathName | !singularize>> resource can be found
```

**Comment by zero51** [comment]
The line numbers in the parse errors don't ever seem to be anything other than 1, but the other two parse errors are a result of this line...

```
description: Base64 encoded version of <identifier>:<secret>, prefaced with 'Basic'
```

**Comment by jstoiko** [comment]
Your issue seems related to what was reported here: https://github.com/mulesoft/osprey/issues/130.

Have you tried to parse your file using the [parser](https://github.com/raml-org/raml-js-parser-2) directly? It seems like using the latest version might fix the issue you are reporting. If it does, then we should probably bump the version in Osprey. If it doesn't, then I suggest you file an issue [here](https://github.com/raml-org/raml-js-parser-2/issues).

**Comment by zero51** [comment]
OK, will have a look. I guess the `additionalProperties` issue still stands though?

**Comment by jstoiko** [comment]
I can't reproduce, i.e. `additionalProperties` works for me. Can you share a RAML snippet here?

**Comment by zero51** [comment]
For this endpoint...
```
        patch:
          body:
            type: object
            properties:
              first_name?: string
              last_name?: string
            additionalProperties: false
            minProperties: 1
```

An empty body `{}` correctly throws...
```
invalid json (minProperties, 1)
```

However, the following bodies are permitted: `{"foo": "bar"}` and `{"first_name": "Fred", "foo": "bar"}`.
