### ISSUE TITLE
RAML data types with empty objects are not handled properly

### ISSUE THREAD

**Issue by blai** [mulesoft/osprey#140]
This works
```yaml
types:
  Foo:
    type: object

/foo:
  put:
    application/json:
      type: Foo
```

while this does not:
```yaml
/foo:
  put:
    application/json:
      type: object
```

it throws the following exception
```
SyntaxError: Unable to compile JSON schema for put /foo: Unexpected token o
    at Object.parse (native)
    at jsonBodyValidationHandler (/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:432:21)
    at jsonBodyHandler (/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:353:21)
    at /node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:296:29
```
