### ISSUE TITLE
Issue with adding a property called `type` to an object

### ISSUE THREAD

**Issue by TwoPlusTwoOne** [mulesoft/osprey#182]
When defining the body for a post method, if I define the body to be an object with a property called `type`, the behavior is flaky and incorrect.

For example:

```
/postMethod:
  post:
    body:
      type: object
      properties:
        name: string
        age: number
        type: string
```

Will create a validation where the body of `/postMethod` is expected to be a `string` rather than an `object`. This is because the parser interprets the `type` property to be referring to the type of the object, rather than a property of the object
