### ISSUE TITLE
Query parameter object support + webapi-parser

### ISSUE THREAD

**Issue by davidsims9t** [mulesoft/osprey#203]
Hello,

Is there any support for supporting query strings with object query parameters (i.e. "fields[key1]=1&fields[key2]=1")? It seems like RAML supports this.

Also do you have any idea when raml-1-parser will be replaced with webapi-parser?

Thanks,
David

**Comment by jstoiko** [comment]
Osprey [v1.0.0](https://github.com/mulesoft/osprey/releases/tag/v1.0.0) has been released and is now based on `webapi-parser` instead of the now deprecated `raml-1-parser`. I'll leave this issue open so you have a chance to try it and make sure it addresses your concern around query parameters support. Looking forward to here back.

**Comment by davidsims9t** [comment]
@jstoiko I tried using v1.0.0, but it looks like object query parameters don't seem to work. This is what my RAML definition looks like:

```
get:
queryParameters:
/^fields\[[a-zA-Z0-9]\]+$/:
                    type: string
                    description: List of fields to display in JSON
                    required: false
```
